### ISSUE TITLE
untrusted certificate on apps.owncloud.com

### ISSUE THREAD

**Issue by dh-connect** [owncloud/owncloud.org#1105]
don't know if this is right here, but my OC can't access the oc app store, reason seems to be the certificate:

Could not get application: cURL error 60: SSL certificate problem: unable to get local issuer certificate

wget https://apps.owncloud.com:
ERROR: The certificate of ‘apps.owncloud.com’ is not trusted.
ERROR: The certificate of ‘apps.owncloud.com’ hasn't got a known issuer.

**Comment by RealRancor** [comment]
Hi,

the correct issue tracker would be https://github.com/owncloud/appstore-issues/issues but i think we can keep that in here.

We noticed the issue itself also at central: https://central.owncloud.org/t/curl-60-certificate-issue-with-appstore/4115

Seems it is caused by the move to Let's Encrypt yesterday. The server is not sending a correct certificate chain:

https://www.ssllabs.com/ssltest/analyze.html?d=apps.owncloud.com

and so curl and wget seems to show the issue where Firefox is happily accessing https://apps.owncloud.com

Maybe @danimo can help here to fix the server so it is sending the correct certificate chain.

**Comment by PVince81** [comment]
@DeepDiver1975 @jnweiger @crrodriguez

**Comment by Kawohl** [comment]
@dercorn is on it afaik

**Comment by dercorn** [comment]
@PVince81 @jnweiger @DeepDiver1975 @Kawohl @danimo @felixboehm  I fixed the certificate for https://apps.owncloud.com. Please verify.

**Comment by RealRancor** [comment]
@dercorn Thanks for having a look into that. It seems apps.owncloud.com is still not sending a correct certificate chain as seen on https://www.ssllabs.com/ssltest/analyze.html?d=apps.owncloud.com

**Comment by dercorn** [comment]
@RealRancor @felixboehm @jnweiger I fixed apps.owncloud.com and it now has an A+ rating :)

**Comment by RealRancor** [comment]
Really great, thanks!!! Confirmed that this issue is now fixed. 👯

**Comment by RealRancor** [comment]
@dercorn @DeepDiver1975 

Need to bump this again, seems api.owncloud.com still has that problem:

https://www.ssllabs.com/ssltest/analyze.html?d=api.owncloud.com

**Comment by RealRancor** [comment]
Btw. funny to see that the NextCloud guys instantly pointing fingers like "properly hosted platform" and similar: https://github.com/nextcloud/server/issues/2269 https://github.com/strukturag/nextcloud-spreedme/issues/61

🙊

**Comment by dh-connect** [comment]
I can confirm that the new certificate works now, but I still get the error in oc from the app store:
Error 	core 	Could not get application: cURL error 60: SSL certificate problem: unable to get local issuer certificate 

I also installed a new instance of OC without apps with a fresh config file,
but still the ssl problem in oc.

could anyone confirm that the certificate works with the oc app store? Thank you.

**Comment by RealRancor** [comment]
@dh-connect See https://github.com/owncloud/owncloud.org/issues/1105#issuecomment-262548861

**Comment by Kawohl** [comment]
should be fixed by now

**Comment by RealRancor** [comment]
@Kawohl Confirmed. https://www.ssllabs.com/ssltest/analyze.html?d=api.owncloud.com shows no issues anymore and the oC internal appstore is also showing the Categories and App updates again. 👍

**Comment by Kawohl** [comment]
Thanks @dercorn @RealRancor
