### ISSUE TITLE
RSS security feed is broken 

### ISSUE THREAD

**Issue by bfallik** [owncloud/owncloud.org#1373]
Hi,

We're performing a security audit and I wanted to learn about recent OwnCloud security fixes. From https://owncloud.org/security/ I clicked on the RSS link https://dev.owncloud.org/security/feed, which is broken:
```
dev.owncloud.org’s server IP address could not be found.
```

If I drop the 'dev' term I do get a valid RSS feed, but it's not clear to me if this is being kept up to date since the most reset article is from May 2017.

Where can find I find the latest security update information?

Thanks in advance,
brian

**Comment by hurradieweltgehtunter** [comment]
Hi,
thanks for noticing. I fixed it.

**Comment by bfallik** [comment]
@hurradieweltgehtunter thank you for fixing the broken link but I'm still not sure I have an answer to my underlying question.

When I browse that feed I see [0 news items](https://m.simplepie.org/?feed=https%3A%2F%2Fowncloud.org%2Fsecurity%2Ffeed%2F) so I don't know when the most recent security fix was addressed to know if we've applied it or not.

How can I determine if we've missed any recent security updates?

**Comment by hurradieweltgehtunter** [comment]
I'm afraid that this works correctly and 0 is the correct number. We just had a few changes in the security team and the security advisories are not updated atm. 
@settermjd is our security guy. I need to talk to him. Thanks for rising this topic

**Comment by bfallik** [comment]
@hurradieweltgehtunter thanks. You're response is helpful nonetheless since it doesn't give me a false sense of security based on the RSS feed.

**Comment by settermjd** [comment]
Thanks for the issue @bfallik. The feed will be addressed latest of mid next week.

**Comment by hurradieweltgehtunter** [comment]
@settermjd had you had a chance to look into it?
