### ISSUE TITLE
News page sidebar overlaps with articles

### ISSUE THREAD

**Issue by jbtbnl** [owncloud/owncloud.org#299]
This is what's happening:

![screenshot from 2014-08-31 15 11 44](https://cloud.githubusercontent.com/assets/639688/4101999/a6e17be8-3110-11e4-9d89-db9bda776ea1.png)

http://owncloud.org/news/ in Firefox 31.0

**Comment by jospoortvliet** [comment]
Still an issue thanks to @MorrisJobke and his big pictures ;-)
![app store1](https://cloud.githubusercontent.com/assets/551757/5706327/1c5c1792-9a80-11e4-9c71-f987812dbfde.png)

**Comment by MorrisJobke** [comment]
Guys. I fixed the images back then. Always make images just 

```
img {
max-width: 100%;
}
```

and the huge images will go away.

**Comment by tomneedham** [comment]
Hmm there is something up with the css rules here. I've fixed this at least twice now with the same css.

**Comment by MorrisJobke** [comment]
This time it's

```
.masonry-brick {
    max-width: 100%;
}
```

**Comment by RandolfCarter** [comment]
This is still broken:
![owncloud-news](https://cloud.githubusercontent.com/assets/2631274/7858922/a1467f02-053c-11e5-9f83-1f4afaa95e80.png)

The .masonry-brick setting @MorrisJobke mentions would fix it...

**Comment by jospoortvliet** [comment]
Ok, let me see if I can fix it.

**Comment by jospoortvliet** [comment]
Looks like that worked - https://staging.owncloud.org to verify.

**Comment by RandolfCarter** [comment]
Looks good here as well :+1:

**Comment by MorrisJobke** [comment]
Looks good :+1:

**Comment by jospoortvliet** [comment]
Ok, going to ask to deploy the site soon. Just hoping to get #557 merged today, too... Input welcome!

**Comment by jospoortvliet** [comment]
will close as we dealt with it... for now ;-)
