### ISSUE TITLE
revoked certificate on owncloud.org web page

### ISSUE THREAD

**Issue by petrbenedikt** [owncloud/owncloud.org#433]
When accessing https://owncloud.org it shows error page with message that the certificate has been revoked and therefore it's not trustworthy (error code: sec_error_revoked_certificate).

**Comment by danimo** [comment]
Fixed

**Comment by webstylr** [comment]
I still get this error while trying to download owncloud.
The download-links for archive and webinstaller each result in the above error.

**Comment by petrbenedikt** [comment]
Me too, the same issue with certificate is on download.owncloud.com. I already submit this information via contact form on their site and waiting for an answer.

**Comment by danimo** [comment]
We're working on deploying new certs everywhere...

**Comment by danimo** [comment]
Should be done now.

**Comment by husisusi** [comment]
No it's NOT!
It's annoying to have issue like this one!
Is it so difficult to install an Intermediate/chain certificate to link it to a trusted root certificate?
You do not need a new certificate, Please just copy Intermediate/chain certificate in your Intermediate bundle path!
https://support.godaddy.com/help/article/5238/installing-an-ssl-certificate-in-apache-centos?locale=de-DE&countrysite=en

**Comment by webstylr** [comment]
Working fine for me now.

**Comment by husisusi** [comment]
Yes! It works now!?!

**Comment by danimo** [comment]
@husisusi Sorry, cannot confirm. This comes out cleanly at both sslyze and ssllabs.com. The chain is established cleanly.

**Comment by husisusi** [comment]
@danimo  It works now! Thanks!
